#!/usr/bin/env bash

GRUB_BTRFS_VERSION=4.12

#
# Desativar grub-btrfs.
#     Normal: "false"
#
# GRUB_BTRFS_DISABLE="true"
#

#
# Nome que aparece no menu Grub.
#     Normal: "Use informações de distribuição de /etc/os-release."
#
# GRUB_BTRFS_SUBMENUNAME="Arch Linux snapshots"
#

#
# Título personalizado.
# Mostra/Oculta "date" "snapshot" "type" "description"
# no menu Grub, ordem personalizada disponível.
#     Normal: ("date" "snapshot" "type" "description")
#
# GRUB_BTRFS_TITLE_FORMAT=("date" "snapshot" "type" "description")
#

#
# Limite o número de instantâneos preenchidos no menu GRUB.
#     Normal: "50"
#
# GRUB_BTRFS_LIMIT="50"
#

#
# Classifique os subvolumes encontrados por "ogeneration",
# "generation", "path" ou "rootid". "-rootid" significa
# listar instantâneo por novos primeiro.
#     Normal: "-rootid"
#
# GRUB_BTRFS_SUBVOLUME_SORT="+ogen,-gen,path,rootid"
#

#
# Mostrar instantâneos encontrados durante o
# procedimento "grub-mkconfig".
#     Normal: "true"
#
# GRUB_BTRFS_SHOW_SNAPSHOTS_FOUND="false"
#

#
# Mostrar o total de instantâneos encontrados durante o
# procedimento "grub-mkconfig".
#     Normal: "true"
#
# GRUB_BTRFS_SHOW_TOTAL_SNAPSHOTS_FOUND="true"
#

#
# "grub-btrfs" detecta automaticamente a maioria dos kernels
# existentes. Se você tiver um ou mais kernels personalizados,
# poderá adicioná-los aqui.
#     Normal: ("")
#
# GRUB_BTRFS_NKERNEL=("kernel-custom" "vmlinux-custom")
#

#
# "grub-btrfs" detecta automaticamente a maioria dos initramfs
# existentes. Se você tiver um ou mais initramfs personalizados,
# poderá adicioná-los aqui.
#     Normal: ("")
#
# GRUB_BTRFS_NINIT=("initramfs-custom.img" "initrd-custom.img" "otherinit-custom.gz")
#

#
# "grub-btrfs" detecta automaticamente a maioria dos
# microcódigos existentes. Se você tiver um ou mais
# microcódigos personalizados, poderá adicioná-los
# aqui.
#     Normal: ("")
#
# GRUB_BTRFS_CUSTOM_MICROCODE=("custom-ucode.img" "custom-uc.img "custom_ucode.cpio")
#

#
# Opções de montagem separadas por vírgulas a serem usadas ao
# inicializar um instantâneo. Eles podem ser definidos aqui,
# bem como na linha "/" dentro das páginas "/etc/fstab" dos
# respectivos instantâneos. As opções de montagem encontradas
# em ambos os locais são combinadas e esta variável tem
# prioridade sobre as entradas `fstab`. NB: Não inclui
# "subvol=..." ou "subvolid=..." aqui.
#     Normal: ""
#
# GRUB_BTRFS_ROOTFLAGS="space_cache,commit=10,norecovery"
#

#
# Ignore o caminho específico durante o procedimento
# de "grub-mkconfig". Somente caminhos exatos são
# ignorados. Exemplo: se `specific path` = @, apenas
# a `@` instantâneo será ignorado.
#     Normal: ("@")
#
GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("@")

#
# Ignore o caminho do prefixo durante o procedimento
# "grub-mkconfig". Qualquer caminho começando com a
# sequência especificada será ignorado. Exemplo: se
# `prefix path` = @, todos os instantâneos começando
# com "@/..." será ignorado.
#     Normal: ("var/lib/docker" "@var/lib/docker" "@/var/lib/docker")
#
GRUB_BTRFS_IGNORE_PREFIX_PATH=("var/lib/docker" "@var/lib/docker" "@/var/lib/docker")

#
# Ignore o tipo/tag específico do instantâneo durante 
# o procedimento de "grub-mkconfig".
#     Normal: ("")
#
# Para snapper:
#     Type = single, pre, post.
#
# Para Timeshift:
#     Tag = boot, ondemand, hourly, daily, weekly, monthly.
#
# GRUB_BTRFS_IGNORE_SNAPSHOT_TYPE=("")
#

#
# Ignore a descrição específica do instantâneo durante 
# o procedimento "grub-mkconfig". Exemplo: timeline.
#     Normal: ("")
#
# GRUB_BTRFS_IGNORE_SNAPSHOT_DESCRIPTION=("")
#

#
# "grub-btrfs" detecta automaticamente sua partição de
# inicialização, localizada na raiz do sistema ou em
# uma partição separada ou em um subvolume, Altere
# para "true" se sua partição de inicialização não
# for detectada como separada.
#     Normal: "false"
#
# GRUB_BTRFS_OVERRIDE_BOOT_PARTITION_DETECTION="true"
#

#
# Localização da pasta que contém a página "grub.cfg".
# Use por grub-btrfs para salvar a página "grub-btrfs.cfg".
# Pode ser grub2 em alguns sistemas. Por exemplo, no
# Unix com EFI: "/boot/efi/EFI/fedora"
#     Normal: "/boot/grub"
#
# GRUB_BTRFS_GRUB_DIRNAME="/boot/grub2"
#

#
# Localização de kernels/initramfs/microcode. Usado por
# "grub-btrfs" para detectar a partição de inicialização
# e a localização de kernels/initrafms/microcodes.
#     Normal: "/boot"
#
# GRUB_BTRFS_BOOT_DIRNAME="/boot"
#

#
# Nome/caminho do plug grub-mkconfig, usado por
# "grub-btrfs.service". Pode ser 'grub2-mkconfig'
# em alguns sistemas (Unix ...). Os caminhos comum
# são /sbin:/bin:/usr/sbin:/usr/bin, se o seu
# caminho estiver faltando, informe-o no projeto
# upstream. Por exemplo, no Unix: "/sbin/grub2-mkconfig"
# Você pode usar apenas o nome ou o caminho completo.
#     Normal: grub-mkconfig
#
# GRUB_BTRFS_MKCONFIG=/usr/bin/grub2-mkconfig
#

#
# Nome do plug grub-script-check, usado por "grub-btrfs".
# Pode ser 'grub2-script-check' em alguns sistemas (Unix ...).
# Por exemplo, no Unix: "grub2-script-check".
#     Normal: grub-script-check
#
# GRUB_BTRFS_SCRIPT_CHECK=grub2-script-check
#

#
# Caminho da página grub-mkconfig_lib, usado por
# "grub-btrfs". Pode ser '/usr/share/grub2/grub-mkconfig_lib'
# em alguns sistemas (Unix ...).
#     Normal: /usr/share/grub/grub-mkconfig_lib
#
# GRUB_BTRFS_MKCONFIG_LIB=/usr/share/grub2/grub-mkconfig_lib
#

#
# Gerenciamento de proteção por senha para submenu,
# instantâneos. Consulte o manual do Grub
# http://localhost/grub/manual/grub/grub.html#Authentication-and-authorisation.
# e este comentário http://localhost/grub-btrfs.
#
# Adicione nomes de pessoas autorizadas separadas
# por vírgula (exemplo,mestre). Quando a proteção
# por senha do Grub está habilitada, a super-pessoa
# é autorizada, não é necessário adicioná-lo.
#     Normal: ""
#
# GRUB_BTRFS_PROTECTION_AUTHORIZED_USERS="exemplo,mestre"
#

#
# Desativar suporte de autenticação para submenu de
# Grub-btrfs somente (--unrestricted) não funciona
# se GRUB_BTRFS_PROTECTION_AUTHORIZED_USERS não
# estiver vazio.
#     Normal: "false"
#
# GRUB_BTRFS_DISABLE_PROTECTION_SUBMENU="true"
#
